---
# MD004/ul-style
MD004: false

# MD007/ul-indent
MD007: false

# MD012/no-multiple-blanks
MD012: false

# MD013 Line length
MD013: false

# MD024/no-duplicate-heading/no-duplicate-header
MD024: false

# MD026/no-trailing-punctuation
MD026: false

# MD029/ol-prefix
MD029: false

# MD030/list-marker-space
MD030: false

# MD033/no-inline-html
MD033: false

# MD034/no-bare-urls
MD034: false

# MD036/no-emphasis-as-heading/no-emphasis-as-header
MD036: false

# MD040/fenced-code-language
MD040: false

# MD041/first-line-heading/first-line-h1
MD041: false
